# Generated by Django 5.1.4 on 2025-01-03 07:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("PracticeApp", "0002_itemcertificate_itemreview_stores"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="Stores",
            new_name="Store",
        ),
    ]
