# Generated by Django 5.1.4 on 2025-01-06 12:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("TweeterApp", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="tweet",
            old_name="test",
            new_name="text",
        ),
    ]
